### ISSUE TITLE
Event Docs?

### ISSUE THREAD

**Issue by LawMixer** [DiscordLuau/Discord-Luau#1]
Hey, I've recently stumbled upon this and it's a cool creation! Any event documentation on what each event is? Thanks!

**Comment by 4x8Matrix** [comment]
Hey'o, whoops - I didn't see this! My bad! :wave: 

> Any event documentation on what each event is?

Plan atm is to get `v0.2.0` ([refactor/discord-luau](https://github.com/4x8Matrix/Discord-Luau/tree/refactor/discord-luau)) into the same condition as `v0.1.0`, upon which, yeah i'll set up Moonwave documentation for the events, classes and what not bundled under Discord-Luau!

There's not an exact time on this yet, but it's high on the list of priorities I need to do :smile:

**Comment by 4x8Matrix** [comment]
I've actually just created a page on the `Wiki` detailing the status for this project :sweat_smile: 

https://github.com/4x8Matrix/Discord-Luau/wiki

**Comment by LawMixer** [comment]
Alrighty, thank you!
