### ISSUE TITLE
Endpoint Duplication in DiscordGuild Methods

### ISSUE THREAD

**Issue by 0xJWLabs** [DiscordLuau/Discord-Luau#5]
In the current implementation of the fetchSlashCommandsAsync and fetchGuildChannels methods within the DiscordGuild objects, there's a duplication of the endpoint used for API requests. Both methods use the same endpoint, which I think is unintentional and could potentially lead to confusion and errors.

To resolve it, I think we just need to replace this on fetchGuildChannels
[*Line 69*](https://github.com/DiscordLuau/Discord-Luau/blob/e4c6aecd36ef977de4de0290a91f4fb7af1f84e2/Package/Classes/Objects/DiscordGuild.luau#L69)
```lua
string.format(DiscordEndpoints.GetGuildApplicationCommands, self.discordClient.discordApplication.id, self.id)
```

to
```lua
string.format(DiscordEndpoints.BotGetGuildChannels, self.id)
```

**Comment by 4x8Matrix** [comment]
Fixed in: https://github.com/DiscordLuau/Discord-Luau/commit/800d58ee3e48d771231e1699153883cc2d84055c
